-- Admin-authored announcements / news shown to players (e.g. "results post
-- Monday after the sync runs"). Authored from the admin panel via the service
-- role; players read only.
create table public.announcements (
  id bigint generated by default as identity primary key,
  title text,
  body text not null,
  pinned boolean not null default false,
  created_at timestamptz not null default now()
);

create index announcements_created_at_idx
  on public.announcements (created_at desc);

alter table public.announcements enable row level security;

-- Read-only for signed-in players. There is deliberately NO insert/update/
-- delete policy: writes happen via the service role (admin authoring), and
-- RLS default-deny blocks authenticated writes regardless of the default
-- table grants — same safe pattern as user_scores.
create policy "announcements readable by authenticated"
  on public.announcements for select to authenticated using (true);
