-- Academy Fantasy schema — see docs/files/ARCHITECTURE.md.
-- Reference (non-user) data: seasons, teams, drivers, season_entries, rounds,
-- sessions, session_results, driver_prices.
-- User data: users, user_teams, user_scores, leagues, league_members, coach_insights.

-- Shared trigger to maintain updated_at.
create function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------------

create table public.seasons (
  id integer generated by default as identity primary key,
  year integer not null unique,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- At most one current season.
create unique index seasons_one_current on public.seasons (is_current) where is_current;

create table public.teams (
  id integer generated by default as identity primary key,
  name text not null,
  country_code text,
  short_name text,
  external_id integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.drivers (
  id integer generated by default as identity primary key,
  full_name text not null,
  short_name text not null,
  country_code text,
  date_of_birth date,
  external_id integer,
  wikipedia_url text,
  wikidata_qid text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Which driver drives for which team in which season, plus their F1 partner.
create table public.season_entries (
  id integer generated by default as identity primary key,
  season_id integer not null references public.seasons(id) on delete cascade,
  driver_id integer not null references public.drivers(id) on delete cascade,
  team_id integer not null references public.teams(id),
  car_number integer,
  f1_partner_team text,
  is_wildcard boolean not null default false,
  rounds integer[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, driver_id)
);
create index season_entries_season_id_idx on public.season_entries (season_id);
create index season_entries_driver_id_idx on public.season_entries (driver_id);
create index season_entries_team_id_idx on public.season_entries (team_id);

create table public.rounds (
  id integer generated by default as identity primary key,
  season_id integer not null references public.seasons(id) on delete cascade,
  round_number integer not null,
  country text,
  circuit_name text,
  date_start date,
  date_end date,
  lock_time timestamptz,  -- team selection locks (= Qualifying start)
  status text not null default 'upcoming' check (status in ('upcoming', 'live', 'complete')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, round_number)
);
create index rounds_season_id_idx on public.rounds (season_id);

create table public.sessions (
  id integer generated by default as identity primary key,
  round_id integer not null references public.rounds(id) on delete cascade,
  session_type text not null check (session_type in ('qualifying', 'race1', 'race2')),
  session_start timestamptz,
  status text not null default 'upcoming' check (status in ('upcoming', 'live', 'complete')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (round_id, session_type)
);
create index sessions_round_id_idx on public.sessions (round_id);

create table public.session_results (
  id integer generated by default as identity primary key,
  session_id integer not null references public.sessions(id) on delete cascade,
  driver_id integer not null references public.drivers(id),
  position integer,       -- finishing position; null if DNF/DSQ/DNS
  grid_position integer,  -- for races; null for quali
  status text not null default 'classified' check (status in ('classified', 'dnf', 'dsq', 'dns')),
  fastest_lap boolean not null default false,
  data_source text not null check (data_source in ('wikipedia', 'manual_admin', 'wikidata')),
  verified_against text,  -- e.g. official URL eyeballed for verification only
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, driver_id)
);
create index session_results_session_id_idx on public.session_results (session_id);
create index session_results_driver_id_idx on public.session_results (driver_id);

create table public.driver_prices (
  id integer generated by default as identity primary key,
  round_id integer not null references public.rounds(id) on delete cascade,
  driver_id integer not null references public.drivers(id) on delete cascade,
  price_millions numeric(4, 1) not null check (price_millions between 4.0 and 15.0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (round_id, driver_id)
);
create index driver_prices_round_id_idx on public.driver_prices (round_id);

-- ---------------------------------------------------------------------------
-- User data
-- ---------------------------------------------------------------------------

-- Extends auth.users. is_admin gates the admin area (results entry, scoring).
create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  favourite_team_id integer references public.teams(id),
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One row per user per round — their pick. Exactly 4 drivers, boost among them.
create table public.user_teams (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  round_id integer not null references public.rounds(id) on delete cascade,
  driver_ids integer[] not null,
  boost_driver_id integer not null,
  transfers_used integer not null default 0,
  wildcard_used boolean not null default false,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, round_id),
  constraint user_teams_four_drivers check (array_length(driver_ids, 1) = 4),
  constraint user_teams_boost_in_team check (boost_driver_id = any (driver_ids))
);
create index user_teams_user_id_idx on public.user_teams (user_id);
create index user_teams_round_id_idx on public.user_teams (round_id);

-- Computed by the scoring engine (service role only).
create table public.user_scores (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  round_id integer not null references public.rounds(id) on delete cascade,
  round_points integer not null,
  boost_points_added integer,
  transfer_penalty integer not null default 0,
  cumulative_points integer not null,
  breakdown jsonb,  -- per-driver scoring details
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, round_id)
);
create index user_scores_user_id_idx on public.user_scores (user_id);
create index user_scores_round_id_idx on public.user_scores (round_id);

create table public.leagues (
  id integer generated by default as identity primary key,
  name text not null,
  invite_code text not null unique,  -- 6 chars, e.g. "MNT-4K"
  owner_id uuid not null references public.users(id) on delete cascade,
  season_id integer not null references public.seasons(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index leagues_owner_id_idx on public.leagues (owner_id);
create index leagues_season_id_idx on public.leagues (season_id);

create table public.league_members (
  league_id integer not null references public.leagues(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (league_id, user_id)
);
create index league_members_user_id_idx on public.league_members (user_id);

-- Cache for Claude Coach responses (insert via service role).
create table public.coach_insights (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  round_id integer not null references public.rounds(id) on delete cascade,
  kind text not null check (kind in ('pre_race', 'post_race', 'driver_take')),
  target_id integer,  -- driver_id when kind = 'driver_take', else null
  content text not null,
  model text,
  tokens_used integer,
  created_at timestamptz not null default now()
);
create index coach_insights_user_id_idx on public.coach_insights (user_id);
create index coach_insights_round_id_idx on public.coach_insights (round_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers (every table that has the column)
-- ---------------------------------------------------------------------------

create trigger set_updated_at before update on public.seasons
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.teams
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.drivers
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.season_entries
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.rounds
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.sessions
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.session_results
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.driver_prices
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.users
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.user_teams
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.user_scores
  for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.leagues
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Auto-provision a public.users row when an auth user is created.
-- ---------------------------------------------------------------------------

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.users (id, display_name)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(new.email, '@', 1)
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
