-- Per-user opt-out for lock-time email reminders. Defaults to true: most
-- players who sign up expect transactional nudges before a round locks, and
-- the toggle in the Home account section + email footer let them opt out.
alter table public.users
  add column reminders_enabled boolean not null default true;

-- Idempotency log for every reminder email we send. The unique constraint on
-- (user_id, round_id, kind) means the cron can be re-run without double-sending
-- — INSERT-before-send with `on conflict do nothing` is the pattern.
create table public.reminder_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  round_id integer not null references public.rounds(id) on delete cascade,
  kind text not null check (kind in ('lock_reminder')),
  sent_at timestamptz not null default now(),
  unique (user_id, round_id, kind)
);

alter table public.reminder_log enable row level security;
-- No client-readable rows: only the service role (cron) touches this table.
-- Players never need to query it; the toggle lives on public.users.
