-- League social feed — per-league text posts, flat replies, and likes.
--
-- Scoped to league members via the existing is_league_member() helper (see
-- 20260523204658_enable_rls.sql). Author display names are exposed ONLY through
-- the SECURITY DEFINER feed RPCs below — the users table stays strict, exactly
-- as league_standings does it. Writes go through Server Actions, but RLS is the
-- real guard (membership + authorship); the actions add length + rate limiting.

-- ---------------------------------------------------------------------------
-- Helpers (SECURITY DEFINER, bypass RLS to avoid policy recursion — same
-- pattern as is_league_member / shares_league_with). post_league_id() is
-- defined after the tables it reads (a language-sql body resolves its table
-- references at creation time).
-- ---------------------------------------------------------------------------

-- True if the current user owns `league` (owners moderate their league's feed).
create function public.is_league_owner(league integer)
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1 from public.leagues
    where id = league and owner_id = (select auth.uid())
  );
$$;

-- True if the current user is a site admin (moderation across every league).
create function public.current_user_is_admin()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select coalesce(
    (select is_admin from public.users where id = (select auth.uid())),
    false
  );
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- Posts: user-authored, or system activity events (round scored, member
-- joined…). A user post has an author; a system post has none.
create table public.league_posts (
  id bigint generated by default as identity primary key,
  league_id integer not null references public.leagues(id) on delete cascade,
  author_id uuid references public.users(id) on delete set null,
  body text not null,
  is_system boolean not null default false,
  system_kind text,  -- e.g. 'round_scored','member_joined' (null for user posts)
  created_at timestamptz not null default now(),
  constraint league_posts_body_len check (char_length(body) between 1 and 500),
  constraint league_posts_author_shape check (
    (is_system and author_id is null) or (not is_system and author_id is not null)
  )
);
-- The feed query and realtime authorization both hit (league_id, recency).
create index league_posts_feed_idx on public.league_posts (league_id, created_at desc);

create table public.league_post_replies (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.league_posts(id) on delete cascade,
  author_id uuid references public.users(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint league_post_replies_body_len check (char_length(body) between 1 and 280)
);
create index league_post_replies_post_idx on public.league_post_replies (post_id, created_at);

create table public.league_post_likes (
  post_id bigint not null references public.league_posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)  -- one like per user per post
);

-- The league a post belongs to — resolves reply/like scoping to the parent
-- post without RLS recursion on league_posts. Defined here (not with the other
-- helpers) because a language-sql body resolves table references at creation.
create function public.post_league_id(p_post bigint)
returns integer
language sql
security definer
set search_path = ''
stable
as $$
  select league_id from public.league_posts where id = p_post;
$$;

-- ---------------------------------------------------------------------------
-- RLS — members read; author writes; author/owner/admin delete. Reply and like
-- scoping resolves the parent post's league via post_league_id().
-- ---------------------------------------------------------------------------

alter table public.league_posts enable row level security;

create policy "read posts in your leagues" on public.league_posts
  for select to authenticated
  using (public.is_league_member(league_id));

-- Only non-system posts, authored as yourself, in a league you're in. System
-- posts are inserted by the service role (which bypasses RLS).
create policy "post to your leagues" on public.league_posts
  for insert to authenticated
  with check (
    not is_system
    and author_id = (select auth.uid())
    and public.is_league_member(league_id)
  );

create policy "delete own post, or moderate as owner/admin" on public.league_posts
  for delete to authenticated
  using (
    author_id = (select auth.uid())
    or public.is_league_owner(league_id)
    or public.current_user_is_admin()
  );

alter table public.league_post_replies enable row level security;

create policy "read replies in your leagues" on public.league_post_replies
  for select to authenticated
  using (public.is_league_member(public.post_league_id(post_id)));

create policy "reply in your leagues" on public.league_post_replies
  for insert to authenticated
  with check (
    author_id = (select auth.uid())
    and public.is_league_member(public.post_league_id(post_id))
  );

create policy "delete own reply, or moderate as owner/admin" on public.league_post_replies
  for delete to authenticated
  using (
    author_id = (select auth.uid())
    or public.is_league_owner(public.post_league_id(post_id))
    or public.current_user_is_admin()
  );

alter table public.league_post_likes enable row level security;

create policy "read likes in your leagues" on public.league_post_likes
  for select to authenticated
  using (public.is_league_member(public.post_league_id(post_id)));

create policy "like posts in your leagues" on public.league_post_likes
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and public.is_league_member(public.post_league_id(post_id))
  );

create policy "remove your own like" on public.league_post_likes
  for delete to authenticated
  using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- Realtime — members receive RLS-scoped change events for their leagues,
-- driving a debounced feed refresh (see the LeagueFeedRealtime component).
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table public.league_posts;
alter publication supabase_realtime add table public.league_post_replies;
alter publication supabase_realtime add table public.league_post_likes;

-- ---------------------------------------------------------------------------
-- Read projections — SECURITY DEFINER so they resolve author display names
-- without opening the users table (same posture as league_standings). Each one
-- gates on membership, so a non-member gets nothing.
-- ---------------------------------------------------------------------------

-- One page of a league's feed, newest first, enriched with author name, like +
-- reply counts, and whether the caller has liked each post.
create or replace function public.league_feed(
  p_league integer,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  author_id uuid,
  author_name text,
  body text,
  is_system boolean,
  system_kind text,
  created_at timestamptz,
  like_count integer,
  reply_count integer,
  liked_by_me boolean
)
language sql
security definer
set search_path = ''
stable
as $$
  select
    p.id,
    p.author_id,
    u.display_name as author_name,
    p.body,
    p.is_system,
    p.system_kind,
    p.created_at,
    (select count(*) from public.league_post_likes l where l.post_id = p.id)::integer,
    (select count(*) from public.league_post_replies r where r.post_id = p.id)::integer,
    exists (
      select 1 from public.league_post_likes l
      where l.post_id = p.id and l.user_id = (select auth.uid())
    )
  from public.league_posts p
  left join public.users u on u.id = p.author_id
  where p.league_id = p_league
    and public.is_league_member(p_league)
  order by p.created_at desc
  limit greatest(p_limit, 0)
  offset greatest(p_offset, 0);
$$;

-- The flat reply thread under one post, oldest first, with author names.
create or replace function public.league_post_thread(p_post bigint)
returns table (
  id bigint,
  author_id uuid,
  author_name text,
  body text,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
  select
    r.id,
    r.author_id,
    u.display_name as author_name,
    r.body,
    r.created_at
  from public.league_post_replies r
  left join public.users u on u.id = r.author_id
  where r.post_id = p_post
    and public.is_league_member(public.post_league_id(p_post))
  order by r.created_at asc;
$$;

-- ---------------------------------------------------------------------------
-- Grants — authenticated only (revoke the default public/anon execute), per the
-- hardening in 20260612153016_tighten_function_grants.sql.
-- ---------------------------------------------------------------------------

revoke execute on function public.post_league_id(bigint) from anon, public;
revoke execute on function public.is_league_owner(integer) from anon, public;
revoke execute on function public.current_user_is_admin() from anon, public;
revoke execute on function public.league_feed(integer, integer, integer) from anon, public;
revoke execute on function public.league_post_thread(bigint) from anon, public;

grant execute on function public.post_league_id(bigint) to authenticated;
grant execute on function public.is_league_owner(integer) to authenticated;
grant execute on function public.current_user_is_admin() to authenticated;
grant execute on function public.league_feed(integer, integer, integer) to authenticated;
grant execute on function public.league_post_thread(bigint) to authenticated;
